#!/usr/bin/env python3

import sys
import json

import autogenerated.validate


def main() -> None:
    if len(sys.argv) < 2:
        print("Error: need at least 1 field_dimensions.json as commandline argument for verification. Exiting.", file=sys.stderr)
        sys.exit(1)

    print("This program will validate {0} files now. If you see error messages or stacktraces then one of the files is invalid.".format(len(sys.argv) - 1))

    for filename in sys.argv[1:]:
        with open(filename, mode="rt", encoding="utf8") as in_f:
            field_dimensions = json.load(in_f)

        autogenerated.validate.validate_https___spl_robocup_org_2021_field_dimensions_schema_json(field_dimensions)

        field_definitions = field_dimensions["field"]

        if ("goalBoxAreaLength" in field_definitions) != ("goalBoxAreaWidth" in field_definitions):
            print('Error: field needs to contain both or "goalBoxAreaLength" and "goalBoxAreaWidth", or none of them. Exiting.', file=sys.stderr)
            sys.exit(1)

    print('All files valid. Done.')


if __name__ == '__main__':
    main()
